# Generated by Django 4.2.16 on 2026-05-05 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность, мин')),
                ('director', models.CharField(blank=True, default='', max_length=255, verbose_name='Режиссёр')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('poster', models.CharField(blank=True, default='', max_length=500, verbose_name='URL постера')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('country', models.CharField(blank=True, default='', max_length=255, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'db_table': 'movies',
                'ordering': ['-rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'verbose_name': 'Жанр фильма',
                'verbose_name_plural': 'Жанры фильмов',
                'db_table': 'movie_genres',
                'unique_together': {('movie', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', through='movies.MovieGenre', to='movies.genre'),
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('watching', 'Смотрю'), ('completed', 'Просмотрено'), ('dropped', 'Брошено')], max_length=20, verbose_name='Статус')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка 1-10')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movies', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фильм пользователя',
                'verbose_name_plural': 'Фильмы пользователей',
                'db_table': 'users_usermovies',
                'ordering': ['-date_updated'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
